---
name: 'Publish npm package'
description: 'Publishes npm package to private Artifact Registry, using snapshot versioning'

inputs:
  credentials_file_path:
    description: 'Path to GCP credentials file'
    required: true

runs:
  using: composite
  steps:

    - name: Check preconditions
      id: 'preconditions'
      shell: bash
      run: |
        PACKAGE_VERSION=$(jq '.version' -r package.json)
        if [ "$PACKAGE_VERSION" != "0.0.1-snapshot" ] ; then
          LINE=$(grep -n '"version":' package.json | cut -d: -f1)
          echo "::error file=package.json,line=${LINE}::Package version must always be \"0.0.1-snapshot\" in source control." >> /dev/stderr
          exit 1
        fi
        PACKAGE_PRIVATE=$(jq '.private' -r package.json)
        if [ "$PACKAGE_PRIVATE" == "true" ] ; then
          LINE=$(grep -n '"private":' package.json | cut -d: -f1)
          echo "SHOULD_PUBLISH=false" >> $GITHUB_OUTPUT
          echo "::warning file=package.json,line=${LINE}::Package is marked private, so will not be published" >> /dev/stderr
        else
          echo "SHOULD_PUBLISH=true" >> $GITHUB_OUTPUT
        fi

    - name: Authenticate Artifact Registry
      if: steps.preconditions.outputs.SHOULD_PUBLISH == 'true'
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ inputs.credentials-file-path }}
      shell: bash
      run: |
        npx google-artifactregistry-auth

    - name: Set SNAPSHOT version
      if: steps.preconditions.outputs.SHOULD_PUBLISH == 'true' && startsWith(github.ref, 'refs/heads')
      shell: bash
      run: |
        npm version 0.0.1-snapshot.$(git log -1 --format=%ct) --no-git-tag-version

    - name: Set RELEASE version
      if: steps.preconditions.outputs.SHOULD_PUBLISH == 'true' && startsWith(github.ref, 'refs/tags')
      shell: bash
      run: |
        npm version ${GITHUB_REF_NAME#v} --no-git-tag-version

    - name: Publish npm package
      if: steps.preconditions.outputs.SHOULD_PUBLISH == 'true'
      shell: bash
      run: |
        npm publish

    - name: Set job summary
      if: steps.preconditions.outputs.SHOULD_PUBLISH == 'true'
      shell: bash
      run: |
        PACKAGE_NAME=$(jq '.name' -r package.json)
        PACKAGE_VERSION=$(jq '.version' -r package.json)
        echo "Published \`${PACKAGE_NAME}\` version \`${PACKAGE_VERSION}\` to Artifact Registry" >> $GITHUB_STEP_SUMMARY
