---
name: 'Publish npm package'
description: 'Publishes npm packages to Google Cloud Artifact Registry'

inputs:
  credentials_file_path:
    description: 'Path to GCP credentials file'
    required: true

outputs:
  name:
    description: 'The published name of the package'
    value: ${{ steps.publish.outputs.name}}
  version:
    description: 'The published package version'
    value: ${{ steps.publish.outputs.version}}

runs:
  using: composite
  steps:

    - name: Check preconditions
      shell: bash
      run: |
        PACKAGE_VERSION=$(jq '.version' -r package.json)
        if [ "$PACKAGE_VERSION" != "0.0.1-snapshot" ] ; then
          LINE=$(grep -n '"version":' package.json | cut -d: -f1)
          echo "::error file=package.json,line=${LINE}::Package version must always be \"0.0.1-snapshot\" in source control." >> /dev/stderr
          exit 1
        fi
        PACKAGE_PRIVATE=$(jq '.private' -r package.json)
        if [ "$PACKAGE_PRIVATE" == "true" ] ; then
          LINE=$(grep -n '"private":' package.json | cut -d: -f1)
          echo "::error file=package.json,line=${LINE}::Package is marked private, so cannot be published" >> /dev/stderr
          exit 1
        fi

    - name: Authenticate Artifact Registry
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ inputs.credentials-file-path }}
      shell: bash
      run: |
        npx google-artifactregistry-auth

    - name: Set SNAPSHOT version
      if: startsWith(github.ref, 'refs/heads')
      shell: bash
      run: |
        npm version 0.0.1-snapshot.$(git log -1 --format=%ct) --no-git-tag-version

    - name: Set RELEASE version
      if: startsWith(github.ref, 'refs/tags')
      shell: bash
      run: |
        npm version ${GITHUB_REF_NAME#v} --no-git-tag-version

    - name: Publish npm package
      id: 'publish'
      shell: bash
      run: |
        npm publish
        echo "version=$(jq '.version' -r package.json)" >> $GITHUB_OUTPUT
        echo "name=$(jq '.name' -r package.json)" >> $GITHUB_OUTPUT

    - name: Set job summary
      shell: bash
      run: |
        echo "Published \`${{ steps.publish.outputs.name}}\` version \`${{ steps.publish.outputs.version }}\` to Artifact Registry" >> $GITHUB_STEP_SUMMARY
